{
 "title": "ValueStream - DevOps Metrics - Event Sources",
 "description": "DevOps Metrics to the Event Source Level",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deployment Rate / Source ([1d])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(webhooks_event_start_total{event_type=\"deploy\"}[1d])) by (event_source)",
     "legendFormat": "{{event_source}}"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (sum(webhooks_event_end_total{event_type=\"deploy\", error=\"false\"}) by (job)  / sum(webhooks_event_end_total{event_type=\"deploy\"}) by (job))) * 100",
     "legendFormat": "all sources"
    },
    {
     "expr": "(1 - (sum(webhooks_event_end_total{event_type=\"deploy\", error=\"false\"}) by (event_source)/ sum(webhooks_event_end_total{event_type=\"deploy\"}) by (event_source))) * 100",
     "legendFormat": "{{ event_source }}"
    }
   ]
  },
  {
   "title": "Deploy Duration - Avg",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(webhooks_event_duration_sum{event_type=\"deploy\"}[1d]) / rate(webhooks_event_duration_count{event_type=\"deploy\"}[1d]))) ",
     "legendFormat": "all sources"
    },
    {
     "expr": "(sum(rate(webhooks_event_duration_sum{event_type=\"deploy\"}[1d])) by (event_source) / sum(rate(webhooks_event_duration_count{event_type=\"deploy\"}[1d])) by (event_source)) ",
     "legendFormat": "{{ event_source }}"
    }
   ]
  },
  {
   "title": "Pull Request Duration - Avg",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(webhooks_event_duration_sum{event_type=\"pull_request\"}[1d]) / rate(webhooks_event_duration_count{event_type=\"pull_request\"}[1d]))) ",
     "legendFormat": "all sources"
    },
    {
     "expr": "(sum(rate(webhooks_event_duration_sum{event_type=\"pull_request\"}[1d])) by (event_source) / sum(rate(webhooks_event_duration_count{event_type=\"pull_request\"}[1d])) by (event_source)) ",
     "legendFormat": "{{event_source}}"
    }
   ]
  },
  {
   "title": "Issue Duration - Avg",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(sum(rate(webhooks_event_duration_sum{event_type=\"issue\"}[1d]) / rate(webhooks_event_duration_count{event_type=\"issue\"}[1d])))",
     "legendFormat": "all sources"
    },
    {
     "expr": "(sum(rate(webhooks_event_duration_sum{event_type=\"issue\"}[1d])) by (event_source) / sum(rate(webhooks_event_duration_count{event_type=\"issue\"}[1d])) by (event_source)) ",
     "legendFormat": "{{event_source}}"
    }
   ]
  },
  {
   "title": "Issue Duration - Avg  ([1d])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webhooks_event_duration_sum{event_type=\"issue\"}[1d]) / rate(webhooks_event_duration_count{event_type=\"issue\"}[1d])) ",
     "legendFormat": "all sources"
    },
    {
     "expr": "sum(rate(webhooks_event_duration_sum{event_type=\"issue\"}[1d])) by (event_source) / sum(rate(webhooks_event_duration_count{event_type=\"issue\"}[1d])) by (event_source)",
     "legendFormat": "{{ event_source }}"
    }
   ]
  },
  {
   "title": "Pull Request Duration - Avg  ([1d])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webhooks_event_duration_sum{event_type=\"pull_request\"}[1d]) / rate(webhooks_event_duration_count{event_type=\"pull_request\"}[1d])) ",
     "legendFormat": "all sources"
    },
    {
     "expr": "sum(rate(webhooks_event_duration_sum{event_type=\"pull_request\"}[1d])) by (event_source) / sum(rate(webhooks_event_duration_count{event_type=\"pull_request\"}[1d])) by (event_source) ",
     "legendFormat": "{{ event_source }}"
    }
   ]
  },
  {
   "title": "Deploy Duration - Avg  ([1d])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webhooks_event_duration_sum{event_type=\"deploy\"}[1d]) / rate(webhooks_event_duration_count{event_type=\"deploy\"}[1d])) ",
     "legendFormat": "all sources"
    },
    {
     "expr": "sum(rate(webhooks_event_duration_sum{event_type=\"deploy\"}[1d])) by (event_source) / sum(rate(webhooks_event_duration_count{event_type=\"deploy\"}[1d])) by (event_source) ",
     "legendFormat": "{{ event_source }}"
    }
   ]
  },
  {
   "title": "Pull Request - Avg In System - [15m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(webhooks_event_duration_sum{event_type=\"pull_request\"}[15m])) by (job) / sum(rate(webhooks_event_duration_count{event_type=\"pull_request\"}[15m])) by (job)) *  (sum(rate(webhooks_event_end_total{event_type=\"pull_request\"}[15m])) by (job))",
     "legendFormat": "all sources"
    },
    {
     "expr": "(sum(rate(webhooks_event_duration_sum{event_type=\"pull_request\"}[15m])) by (event_source) / sum(rate(webhooks_event_duration_count{event_type=\"pull_request\"}[15m])) by (event_source)) *  (sum(rate(webhooks_event_end_total{event_type=\"pull_request\"}[15m])) by (event_source))",
     "legendFormat": "{{ event_source }}"
    }
   ]
  }
 ]
}